<?php

return [
    'tagalog' => [
        // Base profanity
        'putangina', 'puta', 'pota', 'tangina', 'tanga', 'gago', 'gaga', 'ogag', 'ulol',
        'lintik', 'lecheng', 'leche', 'bwisit', 'bobo', 'boba', 'bubu', 'inutil',
        'demonyo', 'demonyita', 'kupal', 'punyeta', 'punieta', 'hindot', 'kantot', 'kantutan',
        'chupa', 'tsupa', 'burat', 'titi', 'puke', 'puki', 'pekpek', 'bayag', 'bayagan',
        'tae', 'taena', 'bilat', 'tarantado', 'tarantada', 'pakshet', 'paksit', 'pakyo',
        'yna', 'yowa', 'yawa', 'buang', 'buangon', 'bakakon', 'giatay', 'amaw', 'kagwang',
        'sira ulo', 'siraulo', 'tonto', 'aswang', 'halimaw', 'kaladkarin', 'salot',
        'walang kwenta', 'walang utak', 'bungal', 'maldita', 'pasaway', 'burara', 'wawa',
        'kawawa', 'utak tanga', 'isip tanga', 'sira utak', 'utak malikot', 'talunan',
        
        // Vowel substitution variants (o->u, i->e)
        'putangena', 'petangina', 'putangena', 'tangen', 'tengina', 'tenga', 'tenge',
        'gegu', 'gago', 'gego', 'gugu', 'ulul', 'elol', 'ulel', 'bubu', 'bebe', 'bobu',
        'bweset', 'bwesit', 'bwusit', 'kupel', 'kapal', 'kapat', 'hendut', 'hondot',
        'kentot', 'kontot', 'kantut', 'tsope', 'chupe', 'tsape', 'puky', 'peke',
        'tarantadu', 'tarentado', 'tarantadu', 'pakshit', 'pekshot', 'yowe', 'yawe',
        'bueng', 'baang', 'buong', 'siraulu', 'seraulo', 'tuntu', 'tuntu', 'tento',
        
        // With suffixes "ka"
        'tanga ka', 'gago ka', 'bobo ka', 'ulol ka', 'bwisit ka', 'hayop ka', 'demonyo ka',
        'kupal ka', 'tarantado ka', 'yawa ka', 'buang ka', 'bakakon ka', 'giatay ka',
        'amaw ka', 'kagwang ka', 'siraulo ka', 'pikon ka', 'asiwa ka', 'aswang ka',
        'halimaw ka', 'kaladkarin ka', 'salot ka', 'sira utak ka', 'utak malikot ka',
        'talunan ka', 'walang kwenta ka', 'bungal ka', 'maldita ka', 'pasaway ka',
        'burara ka', 'wawa ka', 'kawawa ka', 'inutil ka', 'bubu ka', 'looser ka',
        'tae ka', 'leche ka', 'utal ka', 'walang utak ka',
        'tenge ka', 'gegu ka', 'gego ka', 'bubu ka', 'bebe ka', 'ulul ka', 'ulel ka',
        'bweset ka', 'kupel ka', 'tarantadu ka', 'yawe ka', 'yowe ka', 'bueng ka',
        'siraulu ka', 'tuntu ka',
        
        // With suffixes "mo"
        'tangina mo', 'tanga mo', 'gago mo', 'bobo mo', 'leche mo', 'tae mo', 'taena mo',
        'bilat mo', 'punyeta mo', 'hindot mo', 'kantot mo', 'kantutan mo', 'tsupa mo',
        'burat mo', 'titi mo', 'puke mo', 'puki mo', 'pekpek mo', 'bayag mo', 'pakshet mo',
        'pakyo mo', 'yna mo', 'yowa mo', 'yawa mo', 'buang mo', 'bakakon mo', 'giatay mo',
        'amaw mo', 'kagwang mo', 'siraulo mo', 'tarantado mo', 'pikon mo', 'asiwa mo',
        'aswang mo', 'halimaw mo', 'kaladkarin mo', 'salot mo', 'sira utak mo',
        'utak malikot mo', 'talunan mo', 'walang kwenta mo', 'bungal mo', 'maldita mo',
        'pasaway mo', 'burara mo', 'wawa mo', 'kawawa mo', 'inutil mo', 'bubu mo',
        'utal mo', 'demonyo mo', 'kupal mo', 'hayop mo', 'looser mo',
        'tengina mo', 'tenge mo', 'gegu mo', 'gego mo', 'bebe mo', 'ulul mo', 'ulel mo',
        'bweset mo', 'kupel mo', 'hendut mo', 'kentot mo', 'kontot mo', 'kantut mo',
        'tsope mo', 'chupe mo', 'puky mo', 'peke mo', 'tarantadu mo', 'tarentado mo',
        'pakshit mo', 'pekshot mo', 'yawe mo', 'yowe mo', 'bueng mo', 'siraulu mo',
        'tuntu mo',
        
        // Common phrases
        'bwakang ina', 'bwakang ina mo', 'putang ina', 'putang ina mo', 'lecheng ina',
        'yawa nimo', 'tanga n\'ya', 'salot n\'ya', 'inutil n\'ya',
        'utak ng tanga',
        
        // Leetspeak variants
        'ptangina', 'p_ta', 'p0ta', 't4ng1n4', 't@ngina', 'tngn', 'g@g0', 'g4go',
        't@e', 'p_k3', 'pk3', 'p0tangina', 'p0t4', 't1ti', 't!ti', 'p3kpek', 'pkpk',
        'b4yag', 'b@yag', 'put@ngina', 't4ng1na', 'g4g0', 'pk3',
        'ptangina mo', 'p0ta mo', 't4ng1n4 mo', 'tngn mo', 'g@g0 mo', 'g4go mo',
        't@e mo', 'p_k3 mo', 'pk3 mo', 't1ti mo', 't!ti mo', 'p3kpek mo', 'b4yag mo',
        'b@yag mo', 'ptanginamo', 'p0tanginamo', 't1tititi', 't!titi', 'p3kpekk',
        'b4yagb4yag', 'p*tanginamo', 'p*tanginamo mo', 'p0tanginamo mo', 't1tititi mo',
        't!titi mo', 'p3kpekk mo', 'b4yagb4yag mo',
        
        // Repeated letters
        'gagooo', 'putaaa', 'uloloo', 'bwbwisit', 'tanginaa', 'tangtang', 'ogago',
        'tanginamo', 'gagaga', 'putanginamo', 'bububu', 'puhye', 'hindooo', 'kantutanmo',
        'tsupatsupa', 'burattiti', 'pekpekk', 'bayagbayag', 'taetae', 'bilatbilat',
        'tarantadotarantado', 'pakshetpakshet', 'pakyoputangina', 'y@wa', 'buangbuang',
        'bakakonmo', 'giataymo', 'amawmo', 'kagwangmo', 'bwakanginamo', 'lechemo',
        'taemo', 'sirauloo',
        
        // With "ka" repeated variants
        'gagooo ka', 'putaaa ka', 'uloloo ka', 'tanginaa ka', 'tangtang ka', 'ogago ka',
        'tanginamo ka', 'gagaga ka', 'putanginamo ka', 'bububu ka', 'demonyita ka',
        'puhye ka', 'hindooo ka', 'kantutanmo ka', 'tsupatsupa ka', 'burattiti ka',
        'pekpekk ka', 'bayagbayag ka', 'taetae ka', 'bilatbilat ka', 'tarantadotarantado ka',
        'pakshetpakshet ka', 'pakyoputangina ka', 'buangbuang ka', 'bakakonmo ka',
        'giataymo ka', 'amawmo ka', 'kagwangmo ka', 'bwakanginamo ka', 'lechemo ka',
        'ptanginamo ka', 'p0tanginamo ka', 't1tititi ka', 't!titi ka', 'p3kpekk ka',
        'b4yagb4yag ka', 'taemo ka',
        
        // With "mo" repeated variants
        'gagooo mo', 'putaaa mo', 'uloloo mo', 'tanginaa mo', 'tangtang mo', 'ogago mo',
        'tanginamo mo', 'gagaga mo', 'putanginamo mo', 'bububu mo', 'demonyita mo',
        'puhye mo', 'hindooo mo', 'kantutanmo mo', 'tsupatsupa mo', 'burattiti mo',
        'pekpekk mo', 'bayagbayag mo', 'taetae mo', 'bilatbilat mo', 'tarantadotarantado mo',
        'pakshetpakshet mo', 'pakyoputangina mo', 'buangbuang mo', 'bakakonmo mo',
        'giataymo mo', 'amawmo mo', 'kagwangmo mo', 'bwakanginamo mo', 'lechemo mo',
        
        // Combined insults with conjunctions
        'gago\'n', 'gago\'n ka', 'tanga\'n', 'tanga\'n ka', 'bobo\'n', 'bobo\'n ka',
        'ulol\'n', 'ulol\'n ka', 'gago\'t ulol', 'gago\'t bobo', 'bobo\'t tanga',
        'ulol\'t gago', 'tanga\'t ulol', 'tarantado\'t gago', 'tanga\'t bobo',
        'ulol\'t bobo', 'bobo\'t ulol', 'gago\'t tanga', 'gago\'t utal',
        'gago\'t maldita', 'tanga\'t maldita', 'bobo\'t maldita', 'ulol\'t maldita',
        'tarantado\'t maldita', 'gago\'t burara', 'tanga\'t burara', 'bobo\'t burara',
        'ulol\'t burara', 'tanga\'t wawa', 'bobo\'t wawa', 'ulol\'t wawa', 'gago\'t wawa',
        'gago\'t inutil', 'tanga\'t inutil', 'bobo\'t inutil', 'ulol\'t inutil',
        'tanga\'t utak malikot', 'bobo\'t utak malikot', 'ulol\'t utak malikot',
        'gago\'t utak malikot', 'tanga\'t walang kwenta', 'bobo\'t walang kwenta',
        'ulol\'t walang kwenta', 'gago\'t walang kwenta', 'tanga\'t talunan',
        'bobo\'t talunan', 'ulol\'t talunan', 'gago\'t talunan', 'tanga\'t pasaway',
        'bobo\'t pasaway', 'ulol\'t pasaway', 'gago\'t pasaway', 'tanga\'t kaladkarin',
        'bobo\'t kaladkarin', 'ulol\'t kaladkarin', 'gago\'t kaladkarin',
        
        // LGBTQ+ hate speech and discriminatory terms
        'bakla', 'tomboy', 'bading', 'bakla ka', 'tomboy ka', 'bading ka',
        'bakla mo', 'tomboy mo', 'bading mo', 'bakla n\'ya', 'tomboy n\'ya',
        'bakla\'t gago', 'tomboy\'t gago', 'bading\'t gago', 'bakla\'t tanga',
        'tomboy\'t tanga', 'bading\'t tanga', 'putang ina ng mga bakla',
        'putang ina ng mga tomboy', 'gay ka', 'lesbian ka', 'queer ka', 'lgbt ka',
        'bakla sa isip', 'bakla sa ugali', 'tomboy sa ugali', 'bading sa ugali',
        'putang ina sa mga bakla', 'putang ina sa mga tomboy', 'putang ina sa bading',
        'bakla sa lipunan', 'tomboy sa lipunan', 'bading sa lipunan',
        'bakla sa pangkat', 'tomboy sa pangkat', 'bading sa pangkat',
        
        // Racial and ethnic discrimination
        'ibang lahi ka', 'dayuhan ka', 'putang ina ng dayuhan',
        'putang ina ng ibang lahi', 'taga ibang bansa', 'taga ibang lahi',
        'tanga sa lahi', 'gago sa lahi', 'bobo sa lahi', 'ulol sa lahi',
        'walang kwenta sa lahi', 'hindi karapat-dapat sa lahi', 'ibang kulay ka',
        'iba ka sa lahat', 'kakaibang lahi', 'kakaibang etnisidad', 'kakaibang kulay',
        'kakaibang lahi mo', 'kakaibang etnisidad mo', 'kakaibang kulay mo',
        
        // Social exclusion and discrimination
        'hindi normal', 'hindi tama', 'kakaibang tao', 'kakaibang sekswalidad',
        'kakaibang kasarian', 'hindi karaniwan', 'kakaibang ugali', 'kakaibang relihiyon',
        'kakaibang kultura', 'hindi kabilang', 'hindi karapat-dapat', 'ibang grupo',
        'pangit sa lipunan', 'hindi tanggap', 'hindi dapat kasama',
        'hindi dapat kausapin', 'kakaibang pag-uugali', 'kakaibang pananaw',
        'kakaibang paniniwala', 'kakaibang komunidad', 'kakaibang kauri',
        'kakaibang pangkat', 'kakaibang identity', 'hindi ka normal',
        'hindi ka karaniwan', 'hindi ka tanggap', 'hindi ka katanggap-tanggap',
        'kakaibang orientation', 'kakaibang sexual orientation', 'kakaibang gender',
        'kakaibang identity sa lipunan', 'kakaibang ugali sa lipunan',
        'kakaibang kilos sa lipunan', 'kakaibang pamumuhay sa lipunan',
        'hindi karapat-dapat sa klase', 'hindi tanggap sa klase',
        'kakaibang anyo sa klase', 'kakaibang pag-uugali sa klase',
        'kakaibang kilos sa klase', 'kakaibang pamumuhay sa klase',
        'kakaibang personalidad sa klase', 'kakaibang karakter sa klase',
        'kakaibang pananaw sa klase', 'kakaibang paniniwala sa klase',
        'hindi ka nararapat sa komunidad', 'hindi ka kabilang sa komunidad',
        'kakaibang anyo sa komunidad', 'kakaibang pag-uugali sa komunidad',
        'kakaibang kilos sa komunidad', 'kakaibang pamumuhay sa komunidad',
        'kakaibang personalidad sa komunidad', 'kakaibang karakter sa komunidad',
        'kakaibang pananaw sa komunidad', 'kakaibang paniniwala sa komunidad',
        'hindi mo nararapat sa lipunan', 'hindi ka nararapat sa pangkat',
        'hindi ka nararapat sa komunidad', 'hindi mo tanggap sa lipunan',
        'hindi mo tanggap sa pangkat', 'hindi mo tanggap sa komunidad',
        'pangit ka sa lipunan', 'pangit ka sa pangkat', 'pangit ka sa klase',
        'pangit ka sa komunidad', 'walang kwenta ka sa lipunan',
        'walang kwenta ka sa pangkat', 'walang kwenta ka sa klase',
        'walang kwenta ka sa komunidad', 'hindi karapat-dapat sa lipunan',
        'hindi karapat-dapat sa grupo', 'hindi tanggap sa komunidad',
        'pangit ka sa grupo', 'hindi pangkaraniwan', 'hindi ayon sa pamantayan',
        'kakaibang ugali ng tao', 'kakaibang asal ng tao', 'kakaibang kilos ng tao',
        'kakaibang paniniwala ng tao', 'kakaibang pananaw ng tao',
        'hindi karapat-dapat sa pangkat', 'hindi karapat-dapat sa komunidad',
        'kakaibang grupong kinabibilangan', 'kakaibang pangkat ng tao',
        'kakaibang uri', 'kakaibang identity ng tao', 'kakaibang pagkakakilanlan',
        'kakaibang anyo', 'kakaibang hitsura', 'kakaibang katawan',
        'kakaibang pananampalataya', 'kakaibang pamumuhay', 'kakaibang asal',
        'kakaibang kilos', 'kakaibang lipunan', 'kakaibang mukha',
        'kakaibang itsura', 'kakaibang ugali mo', 'kakaibang pananaw mo',
        'kakaibang paniniwala mo', 'kakaibang kultura mo', 'kakaibang pamumuhay sa lipunan',
        'hindi ka karapat-dapat sa lipunan mo', 'hindi ka katanggap-tanggap sa lipunan mo',
        'hindi ka nararapat sa pangkat mo', 'hindi ka nararapat sa komunidad mo',
        'kakaibang personalidad', 'kakaibang karakter', 'kakaibang pagkatao',
        'kakaibang sekswalidad mo', 'kakaibang kasarian mo', 'kakaibang identity mo',
        'kakaibang orientation mo', 'kakaibang gender mo', 'kakaibang sexual orientation mo',
        'kakaibang pag-uugali mo', 'kakaibang kilos mo', 'kakaibang asal mo',
        'kakaibang anyo mo', 'kakaibang itsura mo', 'kakaibang katawan mo',
        'kakaibang relihiyon mo', 'kakaibang pananampalataya mo',
    ],
    
    'threat_patterns' => [
        'patayin', 'saktan', 'pukulin', 'i-eliminate', 'wasakin', 'bugbugin',
        'patayin kita', 'saktan kita', 'pukulin kita', 'bugbugin kita',
        'patayin ang', 'saktan ang', 'pukulin ang', 'mamatay', 'patay',
        'sabunot', 'tadyak', 'suntok', 'sipain', 'suntukin', 'tadyakan',
        'sabunotin', 'paluin', 'sumuntok', 'tadyakin', 'sasaktan',
        'papatayin', 'babarilin', 'sasaksak', 'susugurin', 'dadahasin',
        'papatay', 'baril', 'kutsilyo', 'patalsikin', 'gawing patay',
        'sunugin', 'patayin mo', 'patayin siya', 'papatayin kita', 'papatayin mo',
        'papatayin siya', 'sugatan', 'hampasin', 'pasabugin', 'sumugod',
        'gawing masama', 'pasakitan', 'durugin', 'sugod', 'atake', 'saksak',
        'bala', 'pambubugbog', 'hampas', 'suntukan', 'pamiminsala', 'patayan',
        'pagpatay', 'panghihimasok', 'pambobomba', 'pagsaksak', 'pagpalo',
        'pamumura', 'pamumulot', 'paghalik', 'panggugulo', 'pagsuntok',
        'pamamaril', 'paninira', 'pagpahirap', 'pagkasugat', 'pagpindot',
        'pagtulak', 'pagpabagsak', 'pagbugbog', 'panghihila', 'paghampas',
        'sipa', 'sapak', 'pagputok', 'pamumutol', 'pamumugot', 'pamimura',
        'pagbomba', 'pagbaril', 'pagsabog', 'pananakot', 'panggigipit',
        'paghihiganti', 'pamimugot', 'pagsunog', 'panghaharang', 'paghahagis',
        'pagpunit', 'pang-aabuso', 'pagsipa', 'pagtadyak', 'pambabaril',
        'pagsiksik', 'pagnanakaw',
    ],
    
    'harassment_patterns' => [
        'ipakita', 'isend', 'ibigay', 'send nudes', 'send pics',
        'ipakita puke', 'ipakita titi', 'ipakita pekpek',
        'isend larawan', 'ibigay larawan',
    ],
];
